import os
import re
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
import chromadb
from groq import Groq

# Load environment variables (from .env file)
load_dotenv()

# Setup paths relative to script
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CHROMA_DIR = os.path.join(SCRIPT_DIR, "chroma_db")

# Initialize Local Embeddings Model (Same as ingest.py for compatibility)
# Using a singleton-like lazy loader so it loads once and is cached in memory
_embed_model = None

def get_embed_model():
    global _embed_model
    if _embed_model is None:
        print("Loading SentenceTransformer model ('all-MiniLM-L6-v2') in RAG module...")
        _embed_model = SentenceTransformer("all-MiniLM-L6-v2")
    return _embed_model

# Initialize ChromaDB Client
print(f"RAG connecting to ChromaDB at: {CHROMA_DIR}")
chroma_client = chromadb.PersistentClient(path=CHROMA_DIR)

# Configure similarity threshold
# We set this to 1.25 to give a buffer for valid queries (which can score around 1.12)
# while still securely blocking completely out-of-scope queries (which score > 1.90).
DISTANCE_THRESHOLD = 1.25

def extract_final_answer(raw_text: str) -> str:
    """
    Helper function to strip out any <think>...</think> reasoning blocks 
    generated by reasoning models, leaving only the clean final answer.
    """
    if not raw_text:
        return ""
    # Strip <think> tags and everything inside them
    clean_text = re.sub(r'<think>.*?</think>', '', raw_text, flags=re.DOTALL)
    return clean_text.strip()

# System instructions for the LLM
SYSTEM_PROMPT = """You are a highly precise Drug Information Q&A Assistant.
Your primary role is to answer questions using ONLY the provided drug reference document chunks.

CRITICAL INSTRUCTIONS:
1. Answer the question using ONLY the provided Context. Do NOT make up information or use external knowledge.
2. For EVERY claim or fact you mention, you MUST cite the source document name and page number from the context (e.g., "Source: filename.pdf, Page X").
3. If the context does not contain the answer to the question, or if the context is empty/irrelevant, you MUST state exactly: "I don't have this information in the provided documents." Do NOT attempt to answer, speculate, or extrapolate.
4. Medical Dosing & Advice Guardrail: You are strictly forbidden from providing medical dosing, treatment guidelines, or clinical recommendations unless they are explicitly and word-for-word written in the provided context. If the user asks for advice or dosing not found in the context, refuse to answer and instruct them to consult a healthcare professional.
5. ALWAYS append this disclaimer on a new line at the very end of your response: "Disclaimer: This information is derived from official drug documents and is for educational purposes only. Please consult a healthcare professional for clinical advice or treatment decisions."
"""

def query_rag(query_text: str, history: list = None) -> dict:
    """
    RAG pipeline:
    1. Embed query
    2. Retrieve top-4 chunks from ChromaDB
    3. Filter by distance threshold
    4. Construct prompt with context & history
    5. Query Groq API
    6. Return answer, citations & debug scores
    """
    if history is None:
        history = []
        
    # Default response structure
    default_refusal = (
        "I don't have this information in the provided documents.\n\n"
        "Disclaimer: This information is derived from official drug documents and is for educational purposes only. "
        "Please consult a healthcare professional for clinical advice or treatment decisions."
    )
    
    # 1. Embed user query
    embed_model = get_embed_model()
    query_embedding = embed_model.encode(query_text).tolist()
    
    # 2. Connect to collection and query
    try:
        collection = chroma_client.get_collection("drug_info")
    except Exception:
        # Collection doesn't exist (no ingestion run yet)
        return {
            "answer": "The drug database is currently empty. Please run ingestion first.",
            "citations": [],
            "debug_scores": []
        }
        
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=4
    )
    
    # 3. Apply Distance Threshold Check
    if not results or not results["documents"] or not results["documents"][0]:
        return {
            "answer": default_refusal,
            "citations": [],
            "debug_scores": []
        }
        
    # Extract and print all top-k search results with their distance scores (unfiltered)
    debug_scores = []
    print("\n--- ChromaDB Retrieval Debug Scores ---")
    for idx, (doc, meta, dist) in enumerate(zip(results["documents"][0], results["metadatas"][0], results["distances"][0])):
        source_file = meta.get("source", "Unknown")
        page_num = meta.get("page", 0)
        print(f"Rank {idx+1} | Document: {source_file} (Page {page_num}) | Distance Score: {dist:.4f}")
        debug_scores.append({
            "document": source_file,
            "page": page_num,
            "distance": float(dist)
        })
    print("---------------------------------------\n")
        
    best_distance = results["distances"][0][0]
    print(f"Query: '{query_text}' | Best Match L2 Distance: {best_distance:.4f}")
    
    if best_distance > DISTANCE_THRESHOLD:
        print("-> Match too weak (exceeded threshold). Refusing query.")
        return {
            "answer": default_refusal,
            "citations": [],
            "debug_scores": debug_scores
        }
        
    # Extract documents and metadata for valid matches
    context_chunks = []
    citations = []
    seen_citations = set()
    
    for doc, meta, dist in zip(results["documents"][0], results["metadatas"][0], results["distances"][0]):
        if dist <= DISTANCE_THRESHOLD:
            source_file = meta.get("source", "Unknown")
            page_num = meta.get("page", 0)
            context_chunks.append(f"--- START CHUNK (Source: {source_file}, Page {page_num}) ---\n{doc}\n--- END CHUNK ---")
            
            citation_key = (source_file, page_num)
            if citation_key not in seen_citations:
                seen_citations.add(citation_key)
                citations.append({
                    "document": source_file,
                    "page": page_num
                })
                
    # 4. Construct Prompt
    context_str = "\n\n".join(context_chunks)
    messages = []
    
    # Append System Instructions
    messages.append({
        "role": "system",
        "content": SYSTEM_PROMPT
    })
    
    # Append Conversation History (limit to last 3 turns = 6 messages)
    recent_history = history[-6:]
    for msg in recent_history:
        messages.append({
            "role": msg["role"],
            "content": msg["content"]
        })
        
    # Append the current User query and context
    user_content = f"Context:\n{context_str}\n\nQuestion: {query_text}"
    messages.append({
        "role": "user",
        "content": user_content
    })
    
    # 5. Call Groq LLM API
    groq_api_key = os.environ.get("GROQ_API_KEY")
    if not groq_api_key or "YOUR_GROQ_API_KEY" in groq_api_key:
        return {
            "answer": "Groq API key is missing or not configured in backend/.env. Please configure your key to get replies.",
            "citations": [],
            "debug_scores": debug_scores
        }
        
    groq_model = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
    
    try:
        client = Groq(api_key=groq_api_key)
        response = client.chat.completions.create(
            model=groq_model,
            messages=messages,
            temperature=0.0,  # Minimize creativity to reduce hallucinations
            max_tokens=800
        )
        answer = response.choices[0].message.content
        
        # Clean output using the safety helper function
        clean_answer = extract_final_answer(answer)
        
        # Filter citations list to only return sources actually mentioned in the LLM text
        # Regex matches patterns like: Source: filename.pdf, Page X
        cited_matches = re.findall(r'Source:\s*([a-zA-Z0-9_\-\.]+)\s*,\s*[Pp]age\s*(\d+)', clean_answer)
        
        cited_set = set()
        for doc, page in cited_matches:
            try:
                cited_set.add((doc.strip(), int(page)))
            except ValueError:
                continue
                
        filtered_citations = []
        for cite in citations:
            if (cite["document"], cite["page"]) in cited_set:
                filtered_citations.append(cite)
        
        return {
            "answer": clean_answer,
            "citations": filtered_citations,
            "debug_scores": debug_scores
        }
        
    except Exception as e:
        print(f"Error calling Groq API: {e}")
        return {
            "answer": f"An error occurred while communicating with the language model: {str(e)}",
            "citations": [],
            "debug_scores": debug_scores
        }