import os
import ssl
# Bypass SSL verification to avoid CERTIFICATE_VERIFY_FAILED error when downloading HuggingFace models
ssl._create_default_https_context = ssl._create_unverified_context
os.environ["CURL_CA_BUNDLE"] = ""
os.environ["REQUESTS_CA_BUNDLE"] = ""
os.environ["HF_HUB_DISABLE_SSL_VERIFICATION"] = "1"

import httpx
import urllib3
from huggingface_hub.utils._http import set_client_factory
import huggingface_hub.constants as constants

def custom_client_factory() -> httpx.Client:
    from huggingface_hub.utils._http import hf_request_event_hook
    return httpx.Client(
        verify=False,  # Bypass SSL verification
        event_hooks={"request": [hf_request_event_hook]},
        follow_redirects=True,
        timeout=httpx.Timeout(constants.HF_HUB_DOWNLOAD_TIMEOUT, write=60.0),
    )

set_client_factory(custom_client_factory)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


import re
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
import chromadb
from groq import Groq


# Load environment variables (from .env file)
load_dotenv()

# Setup paths relative to script
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CHROMA_DIR = os.path.join(SCRIPT_DIR, "chroma_db")

# Initialize Local Embeddings Model (Same as ingest.py for compatibility)
# Using a singleton-like lazy loader so it loads once and is cached in memory
_embed_model = None

def get_embed_model():
    global _embed_model
    if _embed_model is None:
        print("Loading SentenceTransformer model ('all-MiniLM-L6-v2') in RAG module...")
        _embed_model = SentenceTransformer("all-MiniLM-L6-v2")
    return _embed_model

# Initialize ChromaDB Client
print(f"RAG connecting to ChromaDB at: {CHROMA_DIR}")
chroma_client = chromadb.PersistentClient(path=CHROMA_DIR)

# Configure similarity threshold
# We set this to 1.25 to give a buffer for valid queries (which can score around 1.12)
# while still securely blocking completely out-of-scope queries (which score > 1.90).
DISTANCE_THRESHOLD = 1.25

def extract_final_answer(raw_text: str) -> str:
    """
    Helper function to strip out any <think>...</think> reasoning blocks 
    generated by reasoning models, leaving only the clean final answer.
    """
    if not raw_text:
        return ""
    # Strip <think> tags and everything inside them
    clean_text = re.sub(r'<think>.*?</think>', '', raw_text, flags=re.DOTALL)
    return clean_text.strip()


def build_prompt(role: str, question: str, retrieved_chunks: str, chat_history: str) -> str:
    """
    Constructs a role-specific system prompt based on user audience role ("doctor" or "patient").
    """
    if role == "doctor":
        persona = """You are a highly precise Drug Information Q&A Assistant.
Your primary role is to answer questions using ONLY the provided drug reference document chunks.
AUDIENCE: CLINICIANS & DOCTORS.
- Use clinical terminology (mechanism of action, contraindications, pharmacokinetics).
- Include full dosage details, drug-drug interactions, and precautions/cautions exactly as stated in the source context.
- Be concise, professional, and direct. Do not simplify, soften, or extrapolate the language.
- State clinical warnings directly and factually.
- Do NOT use outside knowledge. Answer ONLY using the provided Context."""
    else:
        persona = """You are a highly precise Drug Information Q&A Assistant.
Your primary role is to answer questions using ONLY the provided drug reference document chunks.
AUDIENCE: PATIENTS & CARETAKERS.
- Use plain, simple, everyday language. Explain any unavoidable medical terms in parenthetical layman explanations.
- Dosage information is allowed, but must be framed safely:
  - State the standard/typical dosage as written in the document context.
  - Always add this exact caveat: "This is the standard dosage from the label — your doctor may prescribe differently based on your condition. Do not change your dose without consulting them."
  - Never tell the patient to start, stop, increase, or decrease their own current medication based on the chatbot's answer.
  - Focus on general understanding: what the drug is for, how it is typically taken, common side effects, and when to seek medical help.
- Do NOT use outside knowledge. Answer ONLY using the provided Context."""

    return f"""{persona}

Context from drug documents:
{retrieved_chunks}

Conversation history:
{chat_history}

Question: {question}

Answer ONLY using the context above. If the answer isn't in the context, say so clearly.
Cite the source page number(s) for every claim."""


def query_rag(query_text: str, role: str = "doctor", history: list = None) -> dict:
    """
    RAG pipeline:
    1. Embed query
    2. Retrieve top-4 chunks from ChromaDB
    3. Filter by distance threshold
    4. Construct prompt with context & history
    5. Query Groq API
    6. Return answer, citations & debug scores
    """
    # Note: Mid-conversation role switches carry prior chat history over as-is; only the persona for the NEXT answer changes.
    if history is None:
        history = []
        
    # Default response structure
    default_refusal = (
        "I don't have this information in the provided documents.\n\n"
        "Disclaimer: This information is derived from official drug documents and is for educational purposes only. "
        "Please consult a healthcare professional for clinical advice or treatment decisions."
    )
    
    # 1. Embed user query
    embed_model = get_embed_model()
    query_embedding = embed_model.encode(query_text).tolist()
    
    # 2. Connect to collection and query
    try:
        collection = chroma_client.get_collection("drug_info")
    except Exception:
        # Collection doesn't exist (no ingestion run yet)
        return {
            "answer": "The drug database is currently empty. Please run ingestion first.",
            "citations": [],
            "debug_scores": []
        }
        
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=4
    )
    
    # 3. Apply Distance Threshold Check
    if not results or not results["documents"] or not results["documents"][0]:
        return {
            "answer": default_refusal,
            "citations": [],
            "debug_scores": []
        }
        
    # Extract and print all top-k search results with their distance scores (unfiltered)
    debug_scores = []
    print("\n--- ChromaDB Retrieval Debug Scores ---")
    for idx, (doc, meta, dist) in enumerate(zip(results["documents"][0], results["metadatas"][0], results["distances"][0])):
        source_file = meta.get("source", "Unknown")
        page_num = meta.get("page", 0)
        print(f"Rank {idx+1} | Document: {source_file} (Page {page_num}) | Distance Score: {dist:.4f}")
        debug_scores.append({
            "document": source_file,
            "page": page_num,
            "distance": float(dist)
        })
    print("---------------------------------------\n")
        
    best_distance = results["distances"][0][0]
    print(f"Query: '{query_text}' | Best Match L2 Distance: {best_distance:.4f}")
    
    if best_distance > DISTANCE_THRESHOLD:
        print("-> Match too weak (exceeded threshold). Refusing query.")
        return {
            "answer": default_refusal,
            "citations": [],
            "debug_scores": debug_scores
        }
        
    # Extract documents and metadata for valid matches
    context_chunks = []
    citations = []
    seen_citations = set()
    
    for doc, meta, dist in zip(results["documents"][0], results["metadatas"][0], results["distances"][0]):
        if dist <= DISTANCE_THRESHOLD:
            source_file = meta.get("source", "Unknown")
            page_num = meta.get("page", 0)
            context_chunks.append(f"--- START CHUNK (Source: {source_file}, Page {page_num}) ---\n{doc}\n--- END CHUNK ---")
            
            citation_key = (source_file, page_num)
            if citation_key not in seen_citations:
                seen_citations.add(citation_key)
                citations.append({
                    "document": source_file,
                    "page": page_num
                })
                
    # 4. Construct Prompt
    context_str = "\n\n".join(context_chunks)
    
    # Format chat history as a string
    history_str = ""
    if history:
        for msg in history[-6:]:  # Limit to last 3 turns (6 messages)
            role_label = "User" if msg["role"] == "user" else "Assistant"
            history_str += f"{role_label}: {msg['content']}\n"
            
    # Assemble the final single prompt string
    prompt_str = build_prompt(role, query_text, context_str, history_str)
    
    messages = [
        {
            "role": "user",
            "content": prompt_str
        }
    ]
    
    # 5. Call Groq LLM API
    groq_api_key = os.environ.get("GROQ_API_KEY")
    if not groq_api_key or "YOUR_GROQ_API_KEY" in groq_api_key:
        return {
            "answer": "Groq API key is missing or not configured in backend/.env. Please configure your key to get replies.",
            "citations": [],
            "debug_scores": debug_scores
        }
        
    groq_model = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
    
    try:
        # Create a custom HTTP client with SSL verification bypassed to avoid local SSL proxy issues
        http_client = httpx.Client(verify=False)
        client = Groq(api_key=groq_api_key, http_client=http_client)
        response = client.chat.completions.create(
            model=groq_model,
            messages=messages,
            temperature=0.0,  # Minimize creativity to reduce hallucinations
            max_tokens=800
        )
        answer = response.choices[0].message.content
        
        # Clean output using the safety helper function
        clean_answer = extract_final_answer(answer)
        
        # Filter citations list to only return sources actually mentioned in the LLM text
        # Regex matches patterns like: Source: filename.pdf, Page X
        cited_matches = re.findall(r'Source:\s*([a-zA-Z0-9_\-\.]+)\s*,\s*[Pp]age\s*(\d+)', clean_answer)
        
        cited_set = set()
        for doc, page in cited_matches:
            try:
                cited_set.add((doc.strip(), int(page)))
            except ValueError:
                continue
                
        filtered_citations = []
        for cite in citations:
            if (cite["document"], cite["page"]) in cited_set:
                filtered_citations.append(cite)
        
        return {
            "answer": clean_answer,
            "citations": filtered_citations,
            "debug_scores": debug_scores
        }
        
    except Exception as e:
        print(f"Error calling Groq API: {e}")
        return {
            "answer": f"An error occurred while communicating with the language model: {str(e)}",
            "citations": [],
            "debug_scores": debug_scores
        }


if __name__ == "__main__":
    sample_chunks = (
        "--- START CHUNK (Source: rinvoq_pi.pdf, Page 8) ---\n"
        "The recommended dosage of RINVOQ for rheumatoid arthritis is 15 mg once daily. "
        "RINVOQ may be used as monotherapy or in combination with methotrexate or other nonbiologic DMARDs.\n"
        "--- END CHUNK ---"
    )
    sample_history = "User: What is RINVOQ for?\nAssistant: RINVOQ is for rheumatoid arthritis."
    sample_question = "What is the recommended dosage of RINVOQ?"
    
    print("=== VISUAL TEST: build_prompt FOR DOCTOR ===")
    doctor_prompt = build_prompt("doctor", sample_question, sample_chunks, sample_history)
    print(doctor_prompt)
    print("\n" + "="*50 + "\n")
    
    print("=== VISUAL TEST: build_prompt FOR PATIENT ===")
    patient_prompt = build_prompt("patient", sample_question, sample_chunks, sample_history)
    print(patient_prompt)
    print("\n" + "="*50 + "\n")